### ISSUE TITLE
Implement work with apollo-boost

### ISSUE THREAD

**Issue by oleg-am** [blackxored/apollo-link-logger#21]
```
import ApolloClient from 'apollo-boost';
const client = new ApolloClient({
  ...
});
```

**ApolloClient** has different api.

**Comment by blackxored** [comment]
apollo-boost is a preset and hence the exported `ApolloClient` doesn't seem to be the same than https://www.apollographql.com/docs/react/api/apollo-client.html.
I'm not even sure you can override links, if you can then you can use this library as described. Otherwise, I'm afraid there's little we can do on our end.

**Comment by luisfuertes** [comment]
Any update about this? 

Cant override link https://www.apollographql.com/docs/react/essentials/get-started/#apollo-boost
